version: '3.2'
services:
  mysqldb:
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_DATABASE: 'MarketProjectDB'
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - '/var/lib/mysql'
